wandb_version: 1

Threshold:
  desc: null
  value: 1.25
_wandb:
  desc: null
  value:
    cli_version: 0.13.4
    framework: sklearn
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.5
    start_time: 1668947900.189376
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.8.5
      5: 0.13.4
      8:
      - 1
      - 3
      - 5
